
translation_dict = {
    "en_US": {
        ("*", "Mesh display/hide") : "Mesh display/hide",
        ("*", "Hide all meshes except those to which materials are assigned") : "Hide all meshes except those to which materials are assigned",
        ("*", "Display switching") : "Display switching",
        ("*", "Show/hide material") : "Show/hide material",
        ("*", "Drawing Settings") : "Drawing Settings",
        ("*", "Ghost") : "Ghost",
        ("*", "Option Setting") : "Option Setting",
        ("*", "Edit Ghosting Display(Edge)") : "Edit Ghosting Display(Edge)",
        ("*", "Edit Ghosting Display(Face)") : "Edit Ghosting Display(Face)",
        ("*", "Edit Edge color") : "Edit Edge color",
        ("*", "Edit Face color") : "Edit Face color",
        ("*", "Object Ghosting Display(Edge)") : "Object Ghosting Display(Edge)",
        ("*", "Object Ghosting Display(Face)") : "Object Ghosting Display(Face)",
        ("*", "Object Edge color") : "Object Edge color",
        ("*", "Object Face color") : "Object Face color",
        ("*", "Line size") : "Line size",
        ("*", "Display hidden edges as translucent") : "Display hidden edges as translucent",
        ("*", "Display hidden faces as translucent") : "Display hidden faces as translucent",
        ("*", "Hidden edge color") : "Hidden edge color",
        ("*", "Hidden surface color") : "Hidden surface color",
    },
    "ja_JP": {
        ("*", "Mesh display/hide") : "メッシュ表示／非表示",
        ("*", "Hide all meshes except those to which materials are assigned") : "マテリアルが割り当てられたメッシュ以外を非表示にする",
        ("*", "Display switching") : "表示切替",
        ("*", "Show/hide material") : "マテリアルの表示/非表示を切替える",
        ("*", "Drawing Settings") : "半透明描画設定",
        ("*", "Ghost") : "ゴースト",
        ("*", "Option Setting") : "オプション設定",
        ("*", "Ghosting Display1") : "ゴーストを表示(辺)",
        ("*", "Ghosting Display2") : "ゴーストを表示(面)",
        ("*", "Edge color") : "辺の色",
        ("*", "Face color") : "面の色",
        ("*", "Edit Ghosting Display(Edge)") : "[Edit] ゴーストを表示(辺)",
        ("*", "Edit Ghosting Display(Face)") : "[Edit] ゴーストを表示(面)",
        ("*", "Edit Edge color") : "[Edit] 辺の色",
        ("*", "Edit Face color") : "[Edit] 面の色",
        ("*", "Object Ghosting Display(Edge)") : "[Object] ゴーストを表示(辺)",
        ("*", "Object Ghosting Display(Face)") : "[Object] ゴーストを表示(面)",
        ("*", "Object Edge color") : "[Object] 辺の色",
        ("*", "Object Face color") : "[Object] 面の色",
        ("*", "Line size") : "ライン幅",
        ("*", "Display hidden edges as translucent") : "隠れた辺を半透明で表示する",
        ("*", "Display hidden faces as translucent") : "隠れた面を半透明で表示する",
        ("*", "Hidden edge color") : "隠れた辺の色",
        ("*", "Hidden surface color") : "隠れた面の色",
    }
}

