
translation_dict = {
    "en_US": {
        ("*", "Mesh display/hide") : "Mesh display/hide",
        ("*", "Hide all meshes except those to which materials are assigned") : "Hide all meshes except those to which materials are assigned",
        ("*", "Display switching") : "Display switching",
        ("*", "Show/hide material") : "Show/hide material",
        ("*", "Display Material Selection") : "Display Material Selection",
        ("*", "Ghost") : "Ghost",
        ("*", "Option Setting") : "Option Setting",
        ("*", "Ghosting Display1") : "Ghosting Display(Edge)",
        ("*", "Ghosting Display2") : "Ghosting Display(Face)",
        ("*", "Edge color") : "Edge color",
        ("*", "Face color") : "Face color",
        ("*", "Line size") : "Line size",
        ("*", "Display hidden edges as translucent") : "Display hidden edges as translucent",
        ("*", "Display hidden faces as translucent") : "Display hidden faces as translucent",
        ("*", "Hidden edge color") : "Hidden edge color",
        ("*", "Hidden surface color") : "Hidden surface color",
    },
    "ja_JP": {
        ("*", "Mesh display/hide") : "メッシュ表示／非表示",
        ("*", "Hide all meshes except those to which materials are assigned") : "マテリアルが割り当てられたメッシュ以外を非表示にする",
        ("*", "Display switching") : "表示切替",
        ("*", "Show/hide material") : "マテリアルの表示/非表示を切替える",
        ("*", "Display Material Selection") : "表示マテリアルの選択",
        ("*", "Ghost") : "ゴースト",
        ("*", "Option Setting") : "オプション設定",
        ("*", "Ghosting Display1") : "ゴーストを表示(辺)",
        ("*", "Ghosting Display2") : "ゴーストを表示(面)",
        ("*", "Edge color") : "辺の色",
        ("*", "Face color") : "面の色",
        ("*", "Line size") : "ライン幅",
        ("*", "Display hidden edges as translucent") : "隠れた辺を半透明で表示する",
        ("*", "Display hidden faces as translucent") : "隠れた面を半透明で表示する",
        ("*", "Hidden edge color") : "隠れた辺の色",
        ("*", "Hidden surface color") : "隠れた面の色",
    }
}

